// Automatically generated by spice2al
// Version 1.14
// Date: Mon Nov 12 18:30:19 2007
// Input: cells.sp

{
    auto nl;

    nl = makeNetlist( "INVX1" );

    nl->declarePowerNets( "vdd", "gnd" );

    nl->addPMosfet( "M0", 0.5, 0.05, "vdd", "A", "Y", "vdd", "pmos" );
    nl->addNMosfet( "M1", 0.25, 0.05, "gnd", "A", "Y", "gnd", "nmos" );

    nl->addPort( "A" );
    nl->addPort( "Y" );
    nl->addPort( "vdd" );
    nl->addPort( "gnd" );

    nl;
}
